In [ ]:
import numpy as np
import pandas as pd

**DataFrames Basic Operations**

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob"],
    "Department": ["IT", "HR", "IT", "HR", "IT"],
    "Salary": [50000, 40000, 60000, 45000, 55000],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
}

df = pd.DataFrame(data)
df

      Name Department  Salary    City
0    Alice         IT   50000   Delhi
1      Bob         HR   40000  Mumbai
2  Charlie         IT   60000   Delhi
3    Alice         HR   45000    Pune
4      Bob         IT   55000  Mumbai

In [ ]:
df.shape

(5, 4)

In [ ]:
df.columns

Index(['Name', 'Department', 'Salary', 'City'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Department  5 non-null      object
 2   Salary      5 non-null      int64
 3   City        5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [ ]:
df.describe()

            Salary
count      5.00000
mean   50000.00000
std     7905.69415
min    40000.00000
25%    45000.00000
50%    50000.00000
75%    55000.00000
max    60000.00000

In [ ]:
df['Salary'] + 10

0    50010
1    40010
2    60010
3    45010
4    55010
Name: Salary, dtype: int64

In [ ]:
def square(x):
  return x**2

In [ ]:
df["Salary"].apply(square)

0    2500000000
1    1600000000
2    3600000000
3    2025000000
4    3025000000
Name: Salary, dtype: int64

In [ ]:
df["Salary"] = df["Salary"].apply(square)
df

      Name Department      Salary    City
0    Alice         IT  2500000000   Delhi
1      Bob         HR  1600000000  Mumbai
2  Charlie         IT  3600000000   Delhi
3    Alice         HR  2025000000    Pune
4      Bob         IT  3025000000  Mumbai

In [ ]:
df["Miscellenous"] = df["Salary"].apply(lambda x : x/10000)

In [ ]:
df

      Name Department      Salary    City  Miscellenous
0    Alice         IT  2500000000   Delhi      250000.0
1      Bob         HR  1600000000  Mumbai      160000.0
2  Charlie         IT  3600000000   Delhi      360000.0
3    Alice         HR  2025000000    Pune      202500.0
4      Bob         IT  3025000000  Mumbai      302500.0